# SciPy

SciPy é uma coleção de algoritmos matemáticos e funções de conveniência construídas sob Numpy do Python. Ele adiciona poder significativo para a sessão interativa de Python, fornecendo ao usuário comandos e classes de alto nível para manipular e visualizar dados. Com o SciPy, uma sessão interativa de Python torna-se um ambiente de processamento de dados e prototipagem do sistema que rivaliza com sistemas como MATLAB, IDL, Octave, R-Lab e SciLab.

In [1]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,8]])

## Algebra Linear
**linalg**

In [3]:
from scipy import linalg

Determinante de uma matriz

In [4]:
# Calcule o determinante de uma matriz
linalg.det(A)

2.999999999999997

Podemos descobrir os autovalores e os vetores próprios desta matriz:

In [5]:
EW, EV = linalg.eig(A)

In [10]:
EW

array([ 15.55528261+0.j,  -1.41940876+0.j,  -0.13587385+0.j])

In [11]:
EV

array([[-0.24043423, -0.67468642,  0.51853459],
       [-0.54694322, -0.23391616, -0.78895962],
       [-0.80190056,  0.70005819,  0.32964312]])

A solução de sistemas de equações lineares também pode ser feita:

In [12]:
v = np.array([[2],[3],[5]])

In [13]:
v

array([[2],
       [3],
       [5]])

In [14]:
s = linalg.solve(A,v)

In [15]:
s

array([[-2.33333333],
       [ 3.66666667],
       [-1.        ]])

Há muito mais que SciPy é capaz de, como Transformadas de Fourier, etc ...

Dê uma olhada na Documentação para mais detalhes!