In [10]:
import numpy as np
from scipy.linalg import inv

In [2]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,7],[3,1],[1,1]])
c = np.random.rand(3,2)

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
b

array([[4, 7],
       [3, 1],
       [1, 1]])

In [5]:
c

array([[0.78631475, 0.8318566 ],
       [0.06610391, 0.88487785],
       [0.19715068, 0.57372117]])

In [6]:
c.shape

(3, 2)

In [8]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [11]:
iv = inv(a)

In [12]:
iv

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [13]:
a.dot(b)

array([[13, 12],
       [37, 39],
       [61, 66]])

In [14]:
a @ b

array([[13, 12],
       [37, 39],
       [61, 66]])

In [15]:
a * a

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [16]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
iv2 = np.invert(a)

In [18]:
iv2

array([[ -2,  -3,  -4],
       [ -5,  -6,  -7],
       [ -8,  -9, -10]])

In [19]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
det = np.linalg.det(a)

In [21]:
det

-9.51619735392994e-16